name: shell & report
description: Composite action which run shell command(s), capture/print output and report the output to PR
author: Vladimir Chirikov
branding:
  color: gray-dark
  icon: hash
inputs:
  commands:
    required: true
    description: >-
      The bash command(s) to run. The stdout/stderr will be streamed to tty and captured to the output variable.
      You can set multiple commands line by line. The latest command will be captured or the first which returns
      the non-zero exit code. Exit code will be used as result of the action.
      You can use $out to get previous command output, exit_code to get previous command exit_code and $cmd to get the current command line if it's needed.
  token:
    required: false
    description: GitHub Token (Personal access token (PAT)) to create comments.
    default: ${{ github.token }}
  report-start:
    required: false
    description: "If not empty, a command start will be reported using this template."
    default: ""
  report-success:
    required: false
    description: "If not empty, a success result will be reported using this template. You can use {0} in template to paste command output."
    default: ""
  report-failure:
    required: false
    description: "If not empty, a failure will be reported using this template. You can use {0} in template to paste command output."
    default: ""
  message-id:
    required: false
    description: >-
      If empty the message will be repeated, if some other value -
      will try to use existing message with the message-id
    default: ""

outputs:
  out:
    description: "Captured output of the command"
    value: ${{ steps.cmd.outputs.out }}
  dynamic:
    description: JSON dictionary of dynamic output values
    value: ${{ steps.cmd.outputs.dynamic }}
runs:
  using: composite
  steps:
    - name: Report start
      if: ${{ inputs.report-start != '' }}
      uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
      with:
        repo-token: ${{ inputs.token }}
        message: ${{ inputs.report-start }}
        allow-repeats: ${{ fromJSON('["true", "false"]')[inputs.message-id == ''] }}
        message-id: ${{ inputs.message-id }}

    - name: Run the commands
      id: cmd
      uses: vchirikov/.github/shell-action@master
      with:
        commands: ${{ inputs.commands }}
        out-file: /tmp/shell-and-report-action.log

    - name: Format the message
      shell: bash --noprofile --norc {0}
      if: ${{ always() && (inputs.report-success != '' || inputs.report-failure != '') }}
      env:
        outcome: ${{ steps.cmd.outcome }}
        success: ${{ inputs.report-success }}
        failure: ${{ inputs.report-failure }}
      # TODO: should we do something on cancel?
      run: |-
        echo '' > /tmp/shell-and-report-action.msg
        if [[ "$outcome" = "success" ]]; then
          echo "$success" > /tmp/shell-and-report-action.msg
        fi;
        if [[ "$outcome" = "failure" ]]; then
          echo "$failure" > /tmp/shell-and-report-action.msg
        fi;
        sed -i -e '/{0}/{r /tmp/shell-and-report-action.log' -e 'd;}' /tmp/shell-and-report-action.msg

    - name: Report outcome
      # TODO: should we do something on cancel?
      if: ${{ always() && ( (inputs.report-success != '' && steps.cmd.outcome == 'success' ) || (inputs.report-failure != '' && steps.cmd.outcome == 'failure') ) }}
      uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
      with:
        repo-token: ${{ inputs.token }}
        allow-repeats: ${{ fromJSON('["true", "false"]')[inputs.message-id == ''] }}
        message-id: ${{ inputs.message-id }}
        message-path: /tmp/shell-and-report-action.msg
