root: true
env:
  es2022: true
  node: true
plugins:
  - "@typescript-eslint"
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:github/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 10
  sourceType: module
rules:
  quotes:
    - error
    - single
  "@typescript-eslint/ban-ts-comment":
    - "error"
    - ts-expect-error: allow-with-description
      ts-ignore: allow-with-description
      ts-nocheck: true
      ts-check: false
      minimumDescriptionLength: 5
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/consistent-type-imports":
    - error
    - prefer: type-imports
      disallowTypeAnnotations: true
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
  simple-import-sort/imports:
    - error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  no-console: "off"
